name: dailylearn
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  image_picker: ^0.8.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
    - family: Canterbury
      fonts:
        - asset: fonts/Canterbury.ttf

    - family: Bobbers
      fonts:
        - asset: fonts/Bobbers.ttf
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
 
  # fonts:
  # - family: PlayfairDisplay
  #   fonts:
  #     - asset: fonts/PlayfairDisplay-Regular.ttf
  # - family: Schyler
  #   fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
